<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    1.3.6
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>

<div class="page-title">
    <h1><?php echo Mage::getStoreConfig('blog/blog/title'); ?></h1>
</div>

<?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
<?php foreach ($posts as $post): ?>
    <div class="postWrapper">
		<div class="image-blog">
			<?php
				$pattern = "/<img .+\/>/";
				$subject = $post->getPostContent();
				$result = preg_match( $pattern, $subject , $matches , PREG_OFFSET_CAPTURE );
				$matched =$matches[0];
				$first_img=$matched[0];
				//print_r($first_img);
			?>
			
			<a class="img-link" title="<?php echo $post->getTitle(); ?>" href="<?php echo $post->getAddress(); ?>" ><?php echo $first_img;?></a>
		</div>
		
		<div class="info-blog">
			<div class="postTitle">
				<h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
				<h3><?php echo $post->getCreatedTime(); ?></h3>
			</div>
			<div class="postContent">
				<?php $text = str_replace($first_img, '', $post->getPostContent()); 
					echo $text;
				?>
			</div>

			<?php echo $this->getBookmarkHtml($post) ?>

			<div class="postDetails">
				<?php if ($this->getCommentsEnabled()): ?>
					<?php $comment = $post->getCommentCount();?>
				
					<?php if($comment == NULL){?>
						0 <a href="<?php echo $post->getAddress(); ?>#commentBox" > <?php echo Mage::helper('blog')->__('Comment'); ?></a> |
					<?php } else if($comment == 1){?>
						<?php echo $comment; ?> <a href="<?php echo $post->getAddress(); ?>#commentBox" > <?php echo Mage::helper('blog')->__('Comment'); ?></a> |
					<?php } else{?>
						<?php echo $comment; ?> <a href="<?php echo $post->getAddress(); ?>#commentBox" > <?php echo Mage::helper('blog')->__('Comments'); ?></a> |
					<?php }?>
				
				<?php endif; ?>
				<?php $postCats = $post->getCats(); ?>
				<?php if (!empty($postCats)): ?>
					<?php echo Mage::helper('blog')->__('Posted in'); ?>
					<?php foreach ($postCats as $data): ?>
						<a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a>
					<?php endforeach; ?>
				<?php else: ?>
					<?php echo Mage::helper('blog')->__('Posted'); ?>
				<?php endif; ?><?php echo $this->__("By"); ?> <?php echo $post->getUser(); ?>
			</div>
		</div>
		
        
    </div>
<?php endforeach; ?>
<div class="toolbar-bottom">
<?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
</div>
