<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    1.3.6
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $posts = $this->getPosts(); ?>

<div class="title-home">
    <h2><?php echo $this->__('<strong>Latest</strong> Blog') ?></h2>
</div>

<div class="latest-blog">
	<div class="first-post">
	<?php foreach ($posts as $post): ?>

		<div class="blog-item-content">
			<div class="image-blog">
				<?php
					$pattern = "/<img .+\/>/";
					$subject = $post->getPostContent();
					$result = preg_match( $pattern, $subject , $matches , PREG_OFFSET_CAPTURE );
					$matched =$matches[0];
					$first_img=$matched[0];
				?>
				
				<a class="img-link" title="<?php echo $post->getTitle(); ?>" href="<?php echo $post->getAddress(); ?>" ><?php echo $first_img;?></a>
				
			</div>
			
			<div class="info-blog">
				<h2 class="postTitle"><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
								
				<div class="postContent">
					<?php $text = str_replace($first_img, '', $post->getPostContent()); 
						//echo $text;
						echo substr($text,1,150) . '...';
					?>
				</div>
						
			</div>
		</div>

	<?php break;
	endforeach; ?>
	</div>

	<div class="list-post">
	<?php 
	$c = 0;
	foreach ($posts as $post): 
		 if($c==0) {$c++; continue;} ?>
	

    <div class="item item-<?php echo $c; ?>">
		
		<div class="blog-item-content">
			<div class="image-blog">
				<?php
					$pattern = "/<img .+\/>/";
					$subject = $post->getPostContent();
					$result = preg_match( $pattern, $subject , $matches , PREG_OFFSET_CAPTURE );
					$matched =$matches[0];
					$first_img=$matched[0];
				?>
				
				<a class="img-link" title="<?php echo $post->getTitle(); ?>" href="<?php echo $post->getAddress(); ?>" ><?php echo $first_img;?></a>
				
			</div>
			
			<div class="info-blog">
				<h2 class="postTitle"><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
								
				<div class="postContent">
					<?php $text = str_replace($first_img, '', $post->getPostContent()); 
						//echo $text;
						echo substr($text,1,100) . '...';
					?>
				</div>
						
			</div>
		</div>
    </div>
    <?php $c++; if($c==4) {break;} ?>
	<?php endforeach; ?>
	</div>
</div>


