<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    1.3.6
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $posts = $this->getPosts(); ?>

<div class="title-home">
    <h2><span><?php echo $this->__('<strong>Latest</strong> Blog') ?></span></h2>
</div>

<div class="latest-blog">
<?php 
	$c = 0;
	foreach ($posts as $post): 
		$c++;
	?>

    <div class="item item-<?php echo $c; ?>">
		
		
		<div class="blog-item-content">
			<div class="image-blog">
				<?php
					$pattern = "/<img .+\/>/";
					$subject = $post->getPostContent();
					$result = preg_match( $pattern, $subject , $matches , PREG_OFFSET_CAPTURE );
					$matched =$matches[0];
					$first_img=$matched[0];
					
				?>
				
				<a class="img-link" title="<?php echo $post->getTitle(); ?>" href="<?php echo $post->getAddress(); ?>" ><?php echo $first_img;?></a>
			</div>
			
			<div class="info-blog">
				<p class="postTitle"><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></p>
				



				
				<div class="action-post">
					<a class="btn-readmore" title="<?php echo $this->__('Read More')?>" href="<?php echo $post->getAddress(); ?>"><?php echo $this->__('Read More ')?><i class="fa fa-angle-double-right"></i>
</a>
				</div>
			</div>
		</div>
    </div>
    <?php //if($c==4) {break;} ?>
<?php endforeach; ?>
</div>
<script>
	jQuery(document).ready(function($) {
		var owl_brands = $(".latest-blog");
		owl_brands.owlCarousel({
			
			responsive:{
				0:{
					items:1
				},
				480:{
					items:1
				},
				768:{
					items:3
				},
				992:{
					items:4
				},
				1200:{
					items:4
				}
			},

			autoplay:true,
			loop:true,
			nav : true, // Show next and prev buttons
			dots: false,
			autoplaySpeed : 500,
			navSpeed : 500,
			dotsSpeed : 500,
			autoplayHoverPause: true,
			margin:0,

		});	  
	});	
</script>


