<?php
/*------------------------------------------------------------------------
 # SM Basic Products - Version 1.0.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/
$list = $this->_getProducts();
$helper = Mage::helper('basicproducts/data');
if (!empty($list)) { ?>
	<div class="block-bs-list-home">

		<?php if ($this->_getConfig('pretext') != null) { ?>
			<div class="bs-pretext">
				<?php echo $this->_getConfig('pretext'); ?>
			</div>
		<?php } ?>

		<div class="basic-products-megamenu products-grid">
			<!-- Begin bs-items     -->
			<ul class="list-items">
				<?php
				foreach ($list as $_product) { ?>
					<!-- Begin bs-item-cf -->
					<li class="item">
						<!-- Begin bs-item-inner -->
						<div class="item-inner">
							<?php if ($_product->_image) { ?>
							<div class="box-image">								
								<a href="<?php echo $_product->link ?>"
								   title="<?php echo $_product->title; ?>"
									<?php echo $helper->parseTarget($this->_getConfig('product_links_target')); ?>
									>
									<img src="<?php echo $_product->_image; ?>"
										 title="<?php echo $_product->title; ?>"
										 alt="<?php echo $_product->title; ?>"
										>
								</a>												
							</div>
							<?php } ?>
							
							<div class="box-info">
								<?php if ((int)$this->_getConfig('product_title_display', 1)) { ?>
									<h2 class="product-name">
										<a href="<?php echo $_product->link; ?>" title="<?php echo $_product->title; ?>"
											<?php echo $helper->parseTarget($this->_getConfig('product_links_target')); ?>
											>
											<?php echo $helper->truncate($_product->title, $this->_getConfig('product_title_maxlength')); ?>
										</a>
									</h2>
								<?php } ?>
		

								<?php //echo $this->getReviewsSummaryHtml($_product, "short", true); ?>
								<?php if ((int)$this->_getConfig('product_description_display', 1) && $helper->_trimEncode($_product->_description) != '') { ?>
									<div class="bs-description">
										<?php echo $_product->_description; ?>
									</div>
								<?php } ?>

								<?php if ($this->_getConfig('cat_title_display') == 1) { ?>
									<div class="bs-category">
										<a href="<?php echo $_product->catlink; ?>"
										   title="<?php echo $_product->category_title; ?>"
											<?php echo $helper->parseTarget($this->_getConfig('product_links_target')); ?>
											>
											<?php echo 'Category:&nbsp' . $helper->truncate($_product->category_title, $this->_getConfig('category_title_max_characs', 25)); ?>
										</a>
									</div>
								<?php } ?>

								<?php if ($this->_getConfig('item_date_display') == 1) { ?>
									<div class="bs-date">
										<?php echo $_product->created_at; ?>
									</div>
								<?php } ?>

								<?php if ($this->_getConfig('product_source') != 'media') { ?>
									<?php if ((int)$this->_getConfig('product_reviews_count', 1)) { ?>
											<?php
											$this->addReviewSummaryTemplate('sm', 'sm/basicproducts/default_summary.phtml');
											echo $this->getReviewsSummaryHtml($_product, 'sm', true);
											?>
									<?php } ?>

									<?php if ((int)$this->_getConfig('product_price_display', 1)) { ?>
										<?php echo $this->getPriceHtml($_product, true); ?>
									<?php } ?>
								<?php } ?>



								<?php if ($this->_getConfig('product_readmore_display') == 1) { ?>
									<div class="bs-detail">
										<a href="<?php echo $_product->link; ?>"
										   title="<?php echo $_product->title; ?>"
											<?php echo $helper->parseTarget($this->_getConfig('product_links_target')); ?>
											>
											<?php echo $this->_getConfig('product_readmore_text', 'Details'); ?>
										</a>
									</div>
								<?php } ?>

							</div>	
							<?php if ($this->_getConfig('product_source') != 'media') { ?>
							<div class="bottom-action">
								<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
										<a data-toggle="tooltip" data-placement="top" class="btn-action link-compare" title="<?php echo $this->__('Compare') ?>" href="<?php echo $_compareUrl ?>" >
											<span><?php echo $this->__('Compare') ?></span>
										</a>
								<?php endif; ?>
								
								<a href="<?php echo $_product->link; ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"></a>
								<?php if($_product->isSaleable()): ?>
									<button class="btn-action btn-cart" type="button" title="<?php echo $this->__('Add to Cart') ?>"  onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
										<span>
											<span><?php echo $this->__('Add to Cart') ?></span>
										</span>
									</button>
								<?php else: ?>
										<p class="btn-action btn-cart availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
								<?php endif; ?>
																		
									
								<?php if ($this->helper('wishlist')->isAllow()) : ?>
										<a data-toggle="tooltip" data-placement="top" class="btn-action link-wishlist" title="<?php echo $this->__('Wishlist') ?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" >
											<span class="btn-text"><?php echo $this->__('Wishlist') ?></span>
										</a>
								<?php endif; ?>
							</div>		
							<?php } ?>
						</div>

						<!-- End bs-item-inner -->
					</li><!-- End bs-item-cf -->
				<?php } ?>
			</ul>
			<!-- End bs-items -->
		</div><!-- End Sm-basic-products -->
		<?php if ($this->_getConfig('posttext') != null) { ?>
			<div class="bs-posttext">
				<?php echo $this->_getConfig('posttext'); ?>
			</div>
		<?php } ?>
	</div>
<?php
} else {
    echo 'Has no content to show!';
}?>