<?php
/*------------------------------------------------------------------------
 # SM Cart Pro - Version 2.0.0
 # Copyright (c) 2015 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/
$helper = Mage::helper('cartpro/data');
if (!$helper->_getConfig('enable'))
	return;
	
$_cartQty = $this->getSummaryCount();
if(empty($_cartQty)) 
	$_cartQty = 0;

$config = Mage::helper('furnicom/config');
$hdStyle = $config->getThemeLayout('header_style');

?>

<div id="sm_cartpro" class="sm-cartpro">
	<div class="cartpro-title <?php if($_cartQty <= 0): ?> cartpro-empty<?php endif; ?> ">
		<div class="info-minicart">

			<div class="item-info">
				<p><?php echo $this->__('My cart') ?></p>
				<span class="cartpro-count"><?php echo $_cartQty; ?></span><span class="count-tit"><?php echo $this->__(' item(s)'); ?></span>
			</div>
		</div>
	</div>
	<div class="cartpro-content">
		<?php echo $this->getChildHtml('mini_cartpro_content'); ?>
	</div>
</div>
